inherit_from: .rubocop_todo.yml

# Please keep AllCops, Bundler, Layout, Style, Metrics groups and then order cops
# alphabetically
#
# References:
#   * https://github.com/bbatsov/ruby-style-guide
#   * https://rubocop.readthedocs.io/
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - "generators/**/*"
    - "lib/active_merchant/billing/gateways/paypal/**/*"
    - "lib/active_merchant/billing/gateways/paypal_express.rb"
    - "vendor/**/*"
  ExtraDetails: false
  # This setting disables any new cops in updated versions of RuboCop.
  # To complete cleaning up the AM code, this should be removed to enable
  # the cops added to newer versions of RuboCop.
  NewCops: disable
  TargetRubyVersion: 2.5

# Active Merchant gateways are not amenable to length restrictions
Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

