language: ruby
sudo: false
cache: bundler

rvm:
- 2.7
- 2.6
- 2.5

gemfile:
- gemfiles/Gemfile.rails50
- gemfiles/Gemfile.rails51
- gemfiles/Gemfile.rails52
- gemfiles/Gemfile.rails60
- gemfiles/Gemfile.rails_master

jobs:
  include:
      rvm: 2.7
      gemfile: Gemfile
      script: bundle exec rubocop --parallel

notifications:
  email:
    on_success: never
    on_failure: always
